---
# tasks file for php5-fpm

# include variables specific to OS family
- include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Debian'

- include: install.yml
- include: service.yml

