---
# wordpress installation script

- name: download wordpress
  command: /usr/bin/wget -c https://wordpress.org/latest.tar.gz
  args:
    chdir: "{{ wp_srcdir }}"
    creates: "{{ wp_srcdir }}/latest.tar.gz"
  register: wp_download

# document root directory to be created before extracting wordpress

- name: create nginx docroot
  file:
    path: "{{ wp_docroot }}"
    state: directory
    owner: "{{ wp_user }}"
    group: "{{ wp_group }}"

- name: extract wordpress
  shell: "tar -xvf latest.tar.gz && mv wordpress {{ wp_docroot}}/{{ wp_sitedir }}"
  args:
    chdir: "{{ wp_srcdir }}"
    creates: "{{ wp_docroot}}/{{ wp_sitedir }}"
  when: wp_download.rc == 0
