---
# This file will configure nginx server, copy to host system
- name: create default configuration
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
  notify:
    - restart nginx service
- name: copy index.html file
  copy: src=index.html dest=/usr/share/nginx/html/index.html

- name: create php virtual host
  template:
    src: php_vhost.j2
    dest: /etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: "{{ nginx['phpsites'] }}"
  notify:
   - restart nginx service
