---
#www.yml: web server playbook
- hosts: ubuntu
  pre_tasks:
    - name: pre-tasks
      shell: echo 'starting configuration of web server'
  roles:
    - { role: nginx, when: ansible_os_family == 'Debian' }
    - php5-fpm
    - wordpress
  post_tasks:
    - name: post tasks
      shell: echo 'configuration complete'
